
const qt = require("./lib/qt")

const app = new qt.QApplication()
const main = new qt.QMainWindow()
const widget = new qt.QWidget()
const scroll = new qt.QScrollArea()
scroll.setWidget(widget)
scroll.setGeometry(600, 100, 1000, 900)
scroll.setWidgetResizable(true)
widget.setParent(main)
new qt.QLabel(widget).setText("Hello")
new qt.QLabel(widget).setText("Hello")
new qt.QLabel(widget).setText("Hello")
new qt.QLabel(widget).setText("Hello")
new qt.QLabel(widget).setText("Hello")
new qt.QLabel(widget).setText("Hello")
// main.setCentralWidget(scroll)
scroll.wheelEvent((ev) => {
     console.log(ev)
})
console.log(scroll.maximumViewportSize())
main.show()
app.exec()